version: '3.8'
services:
  libasm:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - libasmdata:/Users/larsbonnefoy/projects/libasm
    ports:
      - 2222:22
volumes:
  libasmdata:
