# Use the latest Ubuntu image as the base
FROM ubuntu:latest

# Update package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y gcc gdb vim build-essential nasm && \
    rm -rf /var/lib/apt/lists/*

#Allow ssh auth
#RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Set a default working directory
WORKDIR /workspace

# Start a shell by default
CMD ["bash"]
